// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3YXQeQY4g7KI9bj2SJYCJQ38CcWjWcaw',
    appId: '1:644559826673:web:af95456df1c2b42aa04350',
    messagingSenderId: '644559826673',
    projectId: 'cryptocurrency-tracking',
    authDomain: 'cryptocurrency-tracking.firebaseapp.com',
    storageBucket: 'cryptocurrency-tracking.firebasestorage.app',
    measurementId: 'G-8FXFB33VEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnTH6GS_PQrtUPOfib7DfD8P1YHGV07UI',
    appId: '1:644559826673:android:ab25d21d7d964d18a04350',
    messagingSenderId: '644559826673',
    projectId: 'cryptocurrency-tracking',
    storageBucket: 'cryptocurrency-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrUZnRBRj9zmJbnCGfRICMSnQoOP0Va5g',
    appId: '1:644559826673:ios:b3fa66fa4fdef563a04350',
    messagingSenderId: '644559826673',
    projectId: 'cryptocurrency-tracking',
    storageBucket: 'cryptocurrency-tracking.firebasestorage.app',
    iosBundleId: 'com.example.cryptocurrencyExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrUZnRBRj9zmJbnCGfRICMSnQoOP0Va5g',
    appId: '1:644559826673:ios:b3fa66fa4fdef563a04350',
    messagingSenderId: '644559826673',
    projectId: 'cryptocurrency-tracking',
    storageBucket: 'cryptocurrency-tracking.firebasestorage.app',
    iosBundleId: 'com.example.cryptocurrencyExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3YXQeQY4g7KI9bj2SJYCJQ38CcWjWcaw',
    appId: '1:644559826673:web:e5574c8d373b2717a04350',
    messagingSenderId: '644559826673',
    projectId: 'cryptocurrency-tracking',
    authDomain: 'cryptocurrency-tracking.firebaseapp.com',
    storageBucket: 'cryptocurrency-tracking.firebasestorage.app',
    measurementId: 'G-6PMQDV1DCF',
  );
}
